// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://eneizqrogsmjyihidffv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVuZWl6cXJvZ3NtanlpaGlkZmZ2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ1OTExODMsImV4cCI6MjA3MDE2NzE4M30.K6S0_9klkhCLlOuO90qb8vzM04QWaJANvIwPsMxOHOo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});